CREATE TABLE salas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    room_name VARCHAR(150) NOT NULL,
    room_type VARCHAR(250) NOT NULL,
    localization VARCHAR(350) NOT NULL,
    room_capacity INTEGER NOT NULL
);
